<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <detailPageRefreshMethod>flag</detailPageRefreshMethod>
    <domainWhitelist>
        <domain>tak4hir01.appspot.com</domain>
        <domain>www.google.co.jp</domain>
    </domainWhitelist>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <label>Live Agent コンソール</label>
    <listPlacement>
        <location>left</location>
        <units>percent</units>
        <width>30</width>
    </listPlacement>
    <listRefreshMethod>refreshListRows</listRefreshMethod>
    <tab>standard-LiveChatTranscript</tab>
    <tab>standard-Chatter</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Case</tab>
    <tab>standard-Lead</tab>
    <tab>standard-File</tab>
    <tab>Log__c</tab>
    <tab>ToDo</tab>
    <tab>ActivityTab</tab>
    <tab>verite</tab>
    <tab>Google_Maps</tab>
    <workspaceMappings>
        <mapping>
            <tab>Log__c</tab>
        </mapping>
        <mapping>
            <tab>ToDo</tab>
        </mapping>
        <mapping>
            <tab>standard-Case</tab>
        </mapping>
        <mapping>
            <tab>ActivityTab</tab>
        </mapping>
        <mapping>
            <tab>standard-LiveChatTranscript</tab>
        </mapping>
        <mapping>
            <tab>standard-Contact</tab>
        </mapping>
        <mapping>
            <tab>standard-Chatter</tab>
        </mapping>
        <mapping>
            <tab>verite</tab>
        </mapping>
        <mapping>
            <tab>standard-Lead</tab>
        </mapping>
        <mapping>
            <tab>standard-File</tab>
        </mapping>
        <mapping>
            <tab>Google_Maps</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
